# Generated by Django 5.1.5 on 2025-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.CharField(max_length=255),
        ),
    ]
